### PR TITLE
Feature/build setup

### PR DESCRIPTION
**Pull request by chilimatic**
phing build setup hinzugefügt

### CODE REVIEW

**Comment by andreas83** [comment]
cool, i will review changes as soon as i can.

**Comment by chilimatic** [comment]
no stress, it took me only 15 minutes since I already implemented all of it for other projects. 
I'm open for criticsm :) I just wanted to finish this before I rewrite the database setup with phinx as a migration manager

**Comment by andreas83** [comment]
the new db schema will most likely break some existing code who did not take care about breaking relations...  

did you run the integration test? 
does the delete stuff pass?

**Comment by chilimatic** [comment]
well in my case
-> added a user 
-> wrote something 
-> deleted the user 
-> content is gone 

-> added some content deleted it ... 
the main problem would be to wrap it around your old inconsistent database

 :) but you don't even have to :) its just ment as a fresh base to start the integration on a feature base approach :)

truncating tables most likely won't work ;) but you can always disable the foreign key checks :)

and srsly your integration tests ? :D yes after I fixed it it does :) write more tests :D

**Comment by andreas83** [comment]
> truncating tables most likely won't work ;)

also deleting some data in backend properly wont, like removing a user or content, 
while some comments or likes still relate to each other... 

> but you can always disable the foreign key checks :)

disable the foreign key checks is for sure the wrong way.. :name_badge: 

> write more tests :D

yepp is on my list, you are also welcome to add more.

> the main problem would be to wrap it around your old inconsistent database

so the solution is ? write a migration script who fix the orphaned records.

**Comment by chilimatic** [comment]
> truncating tables most likely won't work ;)
> 
> > also deleting some data in backend properly wont, like removing a user or content,
> > while some comments or likes still relate to each other...

please do explain why :) because I just read it again and I did delete comment via the Backend and as a user. 
maybe I missed something. But based on what I read and tested there are no cascading deadlocks still since I criticise a lot I'm more than willing to learn, if you prove me wrong ... emphasis on prove not feel.

> but you can always disable the foreign key checks :)
> 
> > disable the foreign key checks is for sure the wrong way.. :name_badge:

actually it's common in migration scripts, truncating is a complete state reset via _DDL_, if you delete all entries first and truncate afterwards you would not need it anyway. just open _mysql-workbench_ create a batch migration and read the first instructions :) there is a high chance you see

``` sql
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
```

because during a state change via _DDL_ it makes sense to remove the keys so there are no deadlocks and sequence problems -> what to _delete_/_update_/_drop_ first 

> write more tests :D
> 
> > yepp is on my list, you are also welcome to add more.

Yes I will, Still I'll wait till you wrote enough so we can talk about how to do things based on your experience and not because you read opinion A which contradicts opinion B but you never tried A or B :) you lazy bastard :D ....

> the main problem would be to wrap it around your old inconsistent database
> 
> > so the solution is ? write a migration script who fix the orphaned records.

yes but this is just what you want now, not what this is needed for! If you don't like it I'm not really emotional attached to it there was no _SQL_ bonding time involved I can remove it :)

Just decide don't start a discussion on taste because you're bored or pissed ;)

**Comment by andreas83** [comment]
?

**Comment by chilimatic** [comment]
obviously you didn't want it that way, so lets start from zero :) 
I don't want to waste our time with pointless taste discussions :) 
specify what you want and I will implement it :)

**Pull request closed without merging**
